FROM python:3.12.4-slim

WORKDIR /usr/src/app

# Copiar el código del frontend
COPY frontend/app /usr/src/app/

# Copiar dependencias
COPY ./frontend/env/requirements.txt /usr/src/app/requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install watchdog


EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
